import { auth, db } from './firebase-config.js';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/11.8.1/firebase-auth.js';
import { collection, addDoc, setDoc, doc, deleteDoc, getDocs, getDoc, updateDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/11.8.1/firebase-firestore.js';

const $=id=>document.getElementById(id);const money=n=>(Number(n)||0).toLocaleString('vi-VN')+'đ';const today=()=>new Date().toISOString().slice(0,10);const uid=()=>Math.random().toString(36).slice(2,9);
let currentUser=null,currentPerm={role:'Admin',perms:[]};let editingSale=null,editingStock=null,editingWarranty=null;
const data={customers:[],products:[],staff:[],prices:[],sales:[],stockVouchers:[],receipts:[],warranties:[],users:[],logs:[]};
const modules=['dashboard','sales','debts','inventory','stockbook','warranty','customers','products','prices','staff','reports','permissions'];
const permissionMap={
 Admin:modules.concat(['viewCost','editSales','deleteSales','editStock','deleteStock','audit']),
 Sale:['dashboard','sales','customers','products','warranty'],
 'Kỹ thuật':['dashboard','warranty','customers','products'],
 Kho:['dashboard','inventory','stockbook','products'],
 'Kế toán':['dashboard','debts','reports','sales','customers','products']
};
const permLabels={dashboard:'Dashboard',sales:'Bán hàng',debts:'Công nợ',inventory:'Kho',stockbook:'Sổ kho',warranty:'Bảo hành',customers:'Khách hàng',products:'Sản phẩm',prices:'Bảng giá',staff:'Nhân viên',reports:'Báo cáo',permissions:'Phân quyền',viewCost:'Xem giá vốn/lợi nhuận',editSales:'Sửa đơn bán',deleteSales:'Xóa đơn bán',editStock:'Sửa phiếu kho',deleteStock:'Xóa phiếu kho',audit:'Xem nhật ký'};

function has(p){return currentPerm.role==='Admin'||(currentPerm.perms||[]).includes(p)}
function col(n){return collection(db,n)}
async function loadCol(n){const s=await getDocs(col(n));data[n]=s.docs.map(d=>({id:d.id,...d.data()}));}
async function loadAll(){for(const n of ['customers','products','staff','prices','sales','stockVouchers','receipts','warranties','users']) await loadCol(n); renderAll();}
async function logAction(action,detail){try{await addDoc(col('logs'),{action,detail,email:currentUser?.email||'',at:serverTimestamp()})}catch(e){}}
function fillSelect(el,arr,labelFn,valFn){if(!el)return;el.innerHTML='<option value="">-- Chọn --</option>'+arr.map(x=>`<option value="${valFn?valFn(x):x.id}">${labelFn(x)}</option>`).join('')}
function nextCode(prefix,arr){let max=0;arr.forEach(x=>{const m=String(x.code||'').match(/(\d+)$/);if(m)max=Math.max(max,+m[1])});return prefix+String(max+1).padStart(6,'0')}
function stockOf(code){let qty=0;data.stockVouchers.forEach(v=>(v.items||[]).forEach(it=>{if(it.code===code){if(v.type==='IN')qty+=+it.qty||0;else if(v.type==='OUT')qty-=+it.qty||0;else qty+=+it.qty||0}}));data.sales.forEach(s=>(s.items||[]).forEach(it=>{if(it.code===code)qty-=+it.qty||0}));return qty}
function calcSaleTotals(items,vatMode,paid){let subtotal=items.reduce((a,it)=>a+(+it.qty||0)*(+it.price||0)*(1-(+it.discount||0)/100),0);let rate=vatMode?.includes('10') ? 0.10 : (vatMode?.includes('8') ? 0.08 : 0);let vat=0,grand=subtotal;if(vatMode?.startsWith('add')){vat=subtotal*rate;grand=subtotal+vat}else if(vatMode?.startsWith('included')){vat=subtotal-subtotal/(1+rate);grand=subtotal}return{subtotal,vat,grand,debt:grand-(+paid||0)}}

$('loginBtn').onclick=()=>signInWithEmailAndPassword(auth,$('email').value,$('password').value).catch(e=>alert(e.message));
$('setupAdminBtn').onclick=async()=>{const email=$('email').value,pw=$('password').value;if(!email||!pw)return alert('Nhập email và mật khẩu');const u=await createUserWithEmailAndPassword(auth,email,pw);await setDoc(doc(db,'users',email),{email,name:'Admin',role:'Admin',perms:permissionMap.Admin,createdAt:serverTimestamp()});alert('Đã tạo Admin')};
$('signupStaffBtn').onclick=async()=>{const email=$('email').value,pw=$('password').value;if(!email||!pw)return alert('Nhập email và mật khẩu');const p=await getDoc(doc(db,'users',email));if(!p.exists())return alert('Email chưa được Admin phân quyền');await createUserWithEmailAndPassword(auth,email,pw);alert('Tạo tài khoản nhân viên thành công')};
$('logoutBtn').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{if(!u){$('loginPage').style.display='grid';$('appPage').style.display='none';return}currentUser=u;$('loginPage').style.display='none';$('appPage').style.display='flex';$('currentUser').textContent=u.email;const p=await getDoc(doc(db,'users',u.email));currentPerm=p.exists()?p.data():{role:'Admin',perms:permissionMap.Admin};applyPermissions();await loadAll();});

function applyPermissions(){document.querySelectorAll('#menu button').forEach(b=>{b.style.display=has(b.dataset.page)?'block':'none'});document.querySelectorAll('.view-cost').forEach(x=>x.classList.toggle('hidden',!has('viewCost')));}
document.querySelectorAll('#menu button').forEach(btn=>btn.onclick=()=>showPage(btn.dataset.page));
function showPage(id){if(!has(id))return alert('Tài khoản chưa được phân quyền');document.querySelectorAll('#menu button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));$('pageTitle').textContent=btnTitle(id);$('pageSub').textContent='SIMILOCK ERP - giao diện KAS, quy trình kho/bán hàng theo MISA'}
function btnTitle(id){return ({dashboard:'Dashboard điều hành',sales:'Bán hàng',debts:'Công nợ',inventory:'Kho MISA',stockbook:'Sổ kho',warranty:'Bảo hành',customers:'Khách hàng',products:'Sản phẩm',prices:'Bảng giá',staff:'Nhân viên',reports:'Báo cáo',permissions:'Phân quyền'}[id]||id)}

function renderAll(){applyPermissions();renderSelectors();renderDashboard();renderCustomers();renderProducts();renderPrices();renderStaff();renderSales();renderDebts();renderReceipts();renderStock();renderStockBook();renderWarranties();renderReports();renderPermissions();resetSaleForm();resetStockForm();}
function renderSelectors(){fillSelect($('saleStaff'),data.staff.filter(x=>x.dept==='Sale'||x.dept==='Quản lý'),x=>x.name);fillSelect($('saleTech'),data.staff.filter(x=>x.dept==='Kỹ thuật'),x=>x.name);fillSelect($('priceProduct'),data.products,x=>`${x.code} - ${x.name}`,x=>x.code);fillSelect($('receiptCustomer'),data.customers,x=>`${x.name} - ${x.phone||''}`);fillSelect($('wSale'),data.sales,x=>`${x.code} - ${x.customerName||''}`);$('customerList').innerHTML=data.customers.map(c=>`<option value="${c.name} | ${c.phone||''}"></option>`).join('')}
function renderDashboard(){let month=new Date().toISOString().slice(0,7);let sales=data.sales.filter(s=>String(s.date||'').startsWith(month));let rev=sales.reduce((a,s)=>a+(+s.grand||0),0);let profit=sales.reduce((a,s)=>a+(+s.profit||0),0);let debt=calcDebts().reduce((a,d)=>a+d.debt,0);let low=data.products.filter(p=>stockOf(p.code)<=(+p.minStock||3));$('kpiRevenue').textContent=money(rev);$('kpiProfit').textContent=money(profit);$('kpiDebt').textContent=money(debt);$('kpiLowStock').textContent=low.length;const best={};data.sales.forEach(s=>(s.items||[]).forEach(it=>best[it.code]=(best[it.code]||0)+(+it.qty||0)));let rows=Object.entries(best).sort((a,b)=>b[1]-a[1]).slice(0,8);let max=Math.max(1,...rows.map(r=>r[1]));$('bestProducts').innerHTML=rows.length?rows.map(([code,qty])=>{let p=data.products.find(x=>x.code===code)||{};return `<div class="bar-row"><b>${code}</b><div><small>${p.name||''}</small><div class="bar"><i style="width:${qty/max*100}%"></i></div></div><b>${qty}</b></div>`}).join(''):'Chưa có dữ liệu';const st={};data.sales.forEach(s=>{let n=data.staff.find(x=>x.id===s.staffId)?.name||'Khác';st[n]=st[n]||{rev:0,count:0};st[n].rev+=+s.grand||0;st[n].count++});$('topStaff').innerHTML=Object.entries(st).sort((a,b)=>b[1].rev-a[1].rev).slice(0,5).map(([n,v])=>`<tr><td>${n}</td><td>${money(v.rev)}</td><td>${v.count}</td></tr>`).join('');$('latestSales').innerHTML=data.sales.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,6).map(s=>`<tr><td>${s.code}</td><td>${s.customerName||''}</td><td>${money(s.grand)}</td></tr>`).join('');$('lowStockRows').innerHTML=low.map(p=>`<tr><td>${p.code}</td><td>${p.name}</td><td><span class="badge red">${stockOf(p.code)}</span></td></tr>`).join('')||'<tr><td colspan="3">Kho ổn định</td></tr>'}

window.saveCustomer=async()=>{let o={name:$('cName').value,type:$('cType').value,phone:$('cPhone').value,address:$('cAddress').value,discount:+$('cDiscount').value||0,openingDebt:+$('cOpeningDebt').value||0};if(!o.name)return alert('Nhập tên khách');let id=$('cId').value;if(id){await updateDoc(doc(db,'customers',id),o);await logAction('Sửa khách hàng',o.name)}else await addDoc(col('customers'),{...o,createdAt:serverTimestamp()});clearCustomer();await loadAll()}
function clearCustomer(){['cId','cName','cPhone','cAddress'].forEach(i=>$(i).value='');$('cDiscount').value=0;$('cOpeningDebt').value=0}
function renderCustomers(){$('customerTable').innerHTML=data.customers.map(c=>`<tr><td>${c.name}</td><td>${c.type||''}</td><td>${c.phone||''}</td><td>${c.address||''}</td><td>${c.discount||0}%</td><td><button class="btn ghost" onclick="editCustomer('${c.id}')">Sửa</button> <button class="btn danger" onclick="removeDoc('customers','${c.id}')">Xóa</button></td></tr>`).join('')}
window.editCustomer=id=>{let c=data.customers.find(x=>x.id===id);$('cId').value=id;$('cName').value=c.name||'';$('cType').value=c.type||'Khách lẻ';$('cPhone').value=c.phone||'';$('cAddress').value=c.address||'';$('cDiscount').value=c.discount||0;$('cOpeningDebt').value=c.openingDebt||0}
window.quickCreateCustomer=async()=>{let raw=$('saleCustomerSearch').value.trim();if(!raw)return alert('Nhập tên hoặc SĐT khách');let name=raw.split('|')[0].trim();let phone=(prompt('SĐT khách hàng:',raw.split('|')[1]?.trim()||'')||'');let address=prompt('Địa chỉ:', '')||'';await addDoc(col('customers'),{name,type:'Khách lẻ',phone,address,discount:0,openingDebt:0,createdAt:serverTimestamp()});await loadAll();$('saleCustomerSearch').value=`${name} | ${phone}`}

window.saveProduct=async()=>{let o={code:$('pCode').value.trim(),name:$('pName').value,category:$('pCategory').value,cost:+$('pCost').value||0,price:+$('pPrice').value||0,minStock:+$('pMinStock').value||3};if(!o.code||!o.name)return alert('Nhập model và tên');let id=$('pId').value;if(id){await updateDoc(doc(db,'products',id),o);await logAction('Sửa sản phẩm',o.code)}else await addDoc(col('products'),{...o,createdAt:serverTimestamp()});clearProduct();await loadAll()}
function clearProduct(){['pId','pCode','pName'].forEach(i=>$(i).value='');$('pCategory').value='Khóa thông minh';$('pCost').value='';$('pPrice').value='';$('pMinStock').value=3}
function renderProducts(){$('productTable').innerHTML=data.products.map(p=>`<tr><td>${p.code}</td><td>${p.name}</td><td>${p.category||''}</td><td class="view-cost">${money(p.cost)}</td><td>${money(p.price)}</td><td>${stockOf(p.code)}</td><td><button class="btn ghost" onclick="editProduct('${p.id}')">Sửa</button> <button class="btn danger" onclick="removeDoc('products','${p.id}')">Xóa</button></td></tr>`).join('');applyPermissions()}
window.editProduct=id=>{let p=data.products.find(x=>x.id===id);$('pId').value=id;$('pCode').value=p.code||'';$('pName').value=p.name||'';$('pCategory').value=p.category||'';$('pCost').value=p.cost||0;$('pPrice').value=p.price||0;$('pMinStock').value=p.minStock||3}

function activePriceFor(code,type,date=today()){
  const now=String(date||today());
  const list=data.prices.filter(p=>p.code===code&&p.type===(type||'Khách lẻ')&&String(p.active)!=='false')
    .filter(p=>(!p.validFrom||String(p.validFrom)<=now)&&(!p.validTo||String(p.validTo)>=now))
    .sort((a,b)=>String(b.validFrom||'').localeCompare(String(a.validFrom||'')));
  return list[0]||null;
}
function priceStatus(p){
  if(String(p.active)==='false') return ['Ngưng áp dụng','red'];
  const d=today();
  if(p.validTo && String(p.validTo)<d) return ['Hết hạn','red'];
  if(p.validFrom && String(p.validFrom)>d) return ['Sắp áp dụng','orange'];
  return ['Đang áp dụng','green'];
}
window.savePrice=async()=>{
  let o={code:$('priceProduct').value,type:$('priceType').value,price:+$('priceValue').value||0,validFrom:$('priceFrom').value||'',validTo:$('priceTo').value||'',active:$('priceActive').value==='true',note:$('priceNote').value||'',updatedAt:serverTimestamp()};
  if(!o.code)return alert('Chọn model sản phẩm');
  if(!o.price)return alert('Nhập giá bán');
  if(o.validFrom&&o.validTo&&o.validFrom>o.validTo)return alert('Ngày hiệu lực đến phải lớn hơn hoặc bằng ngày bắt đầu');
  let id=$('priceId').value;
  if(id)await updateDoc(doc(db,'prices',id),o);else await addDoc(col('prices'),{...o,createdAt:serverTimestamp()});
  ['priceId','priceValue','priceFrom','priceTo','priceNote'].forEach(i=>$(i).value='');$('priceActive').value='true';await loadAll()
}
function renderPrices(){
  $('priceTable').innerHTML=data.prices.sort((a,b)=>String(a.code||'').localeCompare(String(b.code||''))||String(b.validFrom||'').localeCompare(String(a.validFrom||''))).map(p=>{let st=priceStatus(p);return`<tr><td><b>${p.code}</b></td><td>${p.type}</td><td>${money(p.price)}</td><td>${p.validFrom||'Không giới hạn'} → ${p.validTo||'Không giới hạn'}</td><td><span class="badge ${st[1]}">${st[0]}</span></td><td>${p.note||''}</td><td><button class="btn ghost" onclick="editPrice('${p.id}')">Sửa</button> <button class="btn danger" onclick="removeDoc('prices','${p.id}')">Xóa</button></td></tr>`}).join('')
}
window.editPrice=id=>{let p=data.prices.find(x=>x.id===id);$('priceId').value=id;$('priceProduct').value=p.code;$('priceType').value=p.type;$('priceValue').value=p.price;$('priceFrom').value=p.validFrom||'';$('priceTo').value=p.validTo||'';$('priceActive').value=String(p.active)!=='false'?'true':'false';$('priceNote').value=p.note||'';showPage('prices')}

window.saveStaff=async()=>{let o={name:$('eName').value,dept:$('eDept').value,phone:$('ePhone').value};if(!o.name)return;let id=$('eId').value;if(id)await updateDoc(doc(db,'staff',id),o);else await addDoc(col('staff'),o);$('eId').value='';$('eName').value='';$('ePhone').value='';await loadAll()}
function renderStaff(){$('staffTable').innerHTML=data.staff.map(e=>`<tr><td>${e.name}</td><td>${e.dept}</td><td>${e.phone||''}</td><td><button class="btn ghost" onclick="editStaff('${e.id}')">Sửa</button> <button class="btn danger" onclick="removeDoc('staff','${e.id}')">Xóa</button></td></tr>`).join('')}
window.editStaff=id=>{let e=data.staff.find(x=>x.id===id);$('eId').value=id;$('eName').value=e.name;$('eDept').value=e.dept;$('ePhone').value=e.phone||''}

window.resetSaleForm=()=>{editingSale=null;$('saleCode').value=nextCode('BH',data.sales);$('saleDate').value=today();$('saleCustomerSearch').value='';$('salePaid').value=0;$('saleNote').value='';$('saleItems').innerHTML='';addSaleItem();updateSaleTotals()}
window.addSaleItem=(it={})=>{let tr=document.createElement('tr');tr.innerHTML=`<td><select onchange="saleProductChanged(this)"><option value="">Chọn model</option>${data.products.map(p=>`<option value="${p.code}" ${p.code===it.code?'selected':''}>${p.code}</option>`).join('')}</select></td><td><input value="${it.name||''}" readonly></td><td><input type="number" value="${it.qty||1}" oninput="updateSaleTotals()"></td><td><input type="number" value="${it.price||0}" oninput="updateSaleTotals()"></td><td><input type="number" value="${it.discount||0}" oninput="updateSaleTotals()"></td><td class="line-total">0</td><td><button class="btn danger" onclick="this.closest('tr').remove();updateSaleTotals()">X</button></td>`;$('saleItems').appendChild(tr);updateSaleTotals()}
window.saleProductChanged=sel=>{let p=data.products.find(x=>x.code===sel.value)||{};let tr=sel.closest('tr');tr.children[1].querySelector('input').value=p.name||'';let customer=findCustomerBySearch();let bp=activePriceFor(p.code,customer?.type,$('saleDate')?.value||today());let price=bp?.price||p.price||0;tr.children[3].querySelector('input').value=price;tr.children[4].querySelector('input').value=customer?.discount||0;updateSaleTotals()}
function saleItems(){return [...$('saleItems').querySelectorAll('tr')].map(tr=>({code:tr.children[0].querySelector('select').value,name:tr.children[1].querySelector('input').value,qty:+tr.children[2].querySelector('input').value||0,price:+tr.children[3].querySelector('input').value||0,discount:+tr.children[4].querySelector('input').value||0})).filter(x=>x.code&&x.qty>0)}
window.updateSaleTotals=()=>{let t=calcSaleTotals(saleItems(),$('saleVatMode').value,$('salePaid').value);[...$('saleItems').querySelectorAll('tr')].forEach(tr=>{let q=+tr.children[2].querySelector('input').value||0,pr=+tr.children[3].querySelector('input').value||0,ck=+tr.children[4].querySelector('input').value||0;tr.querySelector('.line-total').textContent=money(q*pr*(1-ck/100))});$('saleSubTotal').textContent=money(t.subtotal);$('saleVat').textContent=money(t.vat);$('saleGrand').textContent=money(t.grand);$('saleDebt').textContent=money(t.debt)};['saleVatMode','salePaid','saleCustomerSearch'].forEach(id=>setTimeout(()=>$(id)?.addEventListener('input',updateSaleTotals),0));
function findCustomerBySearch(){let s=$('saleCustomerSearch').value.toLowerCase();return data.customers.find(c=>s.includes((c.phone||'zzzz').toLowerCase())||s.includes((c.name||'zzzz').toLowerCase()))}
window.saveSale=async()=>{let customer=findCustomerBySearch();if(!customer){await quickCreateCustomer();customer=findCustomerBySearch()}let items=saleItems();if(!items.length)return alert('Chưa có sản phẩm');let totals=calcSaleTotals(items,$('saleVatMode').value,$('salePaid').value);let cost=items.reduce((a,it)=>a+(data.products.find(p=>p.code===it.code)?.cost||0)*it.qty,0);let o={code:$('saleCode').value,date:$('saleDate').value,customerId:customer.id,customerName:customer.name,customerPhone:customer.phone||'',customerAddress:customer.address||'',staffId:$('saleStaff').value,techId:$('saleTech').value,vatMode:$('saleVatMode').value,paid:+$('salePaid').value||0,note:$('saleNote').value,items,...totals,cost,profit:totals.grand-cost,status:totals.debt>0?'Còn nợ':'Đã thu đủ',updatedAt:serverTimestamp()};if(editingSale){if(!has('editSales'))return alert('Không có quyền sửa đơn');await updateDoc(doc(db,'sales',editingSale),o);await logAction('Sửa đơn bán',o.code)}else await addDoc(col('sales'),{...o,createdAt:serverTimestamp()});await loadAll();resetSaleForm()}
function renderSales(){let q=($('saleSearch')?.value||'').toLowerCase();$('saleTable').innerHTML=data.sales.filter(s=>(s.code+s.customerName).toLowerCase().includes(q)).sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(s=>`<tr><td>${s.code}</td><td>${s.date||''}</td><td>${s.customerName||''}</td><td>${money(s.grand)}</td><td>${money(s.paid)}</td><td>${money(s.debt)}</td><td><span class="badge ${s.debt>0?'orange':'green'}">${s.status}</span></td><td><button class="btn ghost" onclick="printSale('${s.id}')">In A5</button> ${has('editSales')?`<button class="btn ghost" onclick="editSale('${s.id}')">Sửa</button>`:''} ${has('deleteSales')?`<button class="btn danger" onclick="removeDoc('sales','${s.id}')">Xóa</button>`:''}</td></tr>`).join('')}
window.editSale=id=>{let s=data.sales.find(x=>x.id===id);editingSale=id;$('saleCode').value=s.code;$('saleDate').value=s.date;$('saleCustomerSearch').value=`${s.customerName} | ${s.customerPhone||''}`;$('saleStaff').value=s.staffId||'';$('saleTech').value=s.techId||'';$('saleVatMode').value=s.vatMode||'none';$('salePaid').value=s.paid||0;$('saleNote').value=s.note||'';$('saleItems').innerHTML='';(s.items||[]).forEach(addSaleItem);updateSaleTotals();showPage('sales')}
window.printSale=id=>{let s=data.sales.find(x=>x.id===id);let html=`<div class="print-a5"><h2 style="text-align:center">PHIẾU BÁN HÀNG</h2><p><b>SIMILOCK ĐÀ NẴNG</b><br>223 Trường Chinh, P. An Khê, TP. Đà Nẵng<br>403 Nguyễn Thái Bình, P. Bảy Hiền, TP.HCM<br>Hotline: 0902950816</p><hr><p><b>Mã phiếu:</b> ${s.code} &nbsp; <b>Ngày:</b> ${s.date}<br><b>Khách hàng:</b> ${s.customerName} - ${s.customerPhone||''}<br><b>Địa chỉ:</b> ${s.customerAddress||''}</p><table><thead><tr><th>Model</th><th>Tên SP</th><th>SL</th><th>Đơn giá</th><th>CK</th><th>Thành tiền</th></tr></thead><tbody>${(s.items||[]).map(it=>`<tr><td>${it.code}</td><td>${it.name}</td><td>${it.qty}</td><td>${money(it.price)}</td><td>${it.discount||0}%</td><td>${money(it.qty*it.price*(1-(it.discount||0)/100))}</td></tr>`).join('')}</tbody></table><p style="text-align:right"><b>Tiền hàng:</b> ${money(s.subtotal)}<br><b>VAT:</b> ${money(s.vat)}<br><b>Tổng tiền:</b> ${money(s.grand)}<br><b>Đã thu:</b> ${money(s.paid)}<br><b>Còn nợ:</b> ${money(s.debt)}</p><div style="display:flex;justify-content:space-between;text-align:center;margin-top:30px"><div>Khách hàng<br><br><br></div><div>Người bán<br><br><br></div><div>Kỹ thuật<br><br><br></div></div></div>`;doPrint(html)}

function calcDebts(){return data.customers.map(c=>{let sales=data.sales.filter(s=>s.customerId===c.id);let total=sales.reduce((a,s)=>a+(+s.grand||0),0)+(+c.openingDebt||0);let paid=sales.reduce((a,s)=>a+(+s.paid||0),0)+data.receipts.filter(r=>r.customerId===c.id).reduce((a,r)=>a+(+r.amount||0),0);return{customer:c,total,paid,debt:total-paid}}).filter(x=>x.total||x.paid||x.debt)}
function renderDebts(){$('debtTable').innerHTML=calcDebts().map(d=>`<tr><td>${d.customer.name}</td><td>${money(d.total)}</td><td>${money(d.paid)}</td><td><b>${money(d.debt)}</b></td><td><button class="btn ghost" onclick="receiptFor('${d.customer.id}')">Thu tiền</button></td></tr>`).join('')}
window.receiptFor=id=>{$('receiptCustomer').value=id;$('receiptDate').value=today();showPage('debts')};window.openReceiptForm=()=>{$('receiptDate').value=today();showPage('debts')}
window.saveReceipt=async()=>{let cid=$('receiptCustomer').value,amount=+$('receiptAmount').value||0;if(!cid||!amount)return alert('Chọn khách và nhập số tiền');let c=data.customers.find(x=>x.id===cid);await addDoc(col('receipts'),{code:nextCode('PT',data.receipts),customerId:cid,customerName:c.name,amount,date:$('receiptDate').value||today(),note:$('receiptNote').value,createdAt:serverTimestamp()});$('receiptAmount').value='';$('receiptNote').value='';await loadAll()}
function renderReceipts(){$('receiptTable').innerHTML=data.receipts.sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(r=>`<tr><td>${r.date}</td><td>${r.customerName}</td><td>${money(r.amount)}</td><td>${r.note||''}</td></tr>`).join('')}

window.resetStockForm=()=>{editingStock=null;$('stockCode').value=nextCode('NK',data.stockVouchers);$('stockDate').value=today();$('stockType').value='IN';$('stockItems').innerHTML='';addStockItem()};$('stockType').addEventListener('change',()=>{$('stockCode').value=nextCode($('stockType').value==='IN'?'NK':$('stockType').value==='OUT'?'XK':'DC',data.stockVouchers)});
window.addStockItem=(it={})=>{let tr=document.createElement('tr');tr.innerHTML=`<td><select onchange="stockProductChanged(this)"><option value="">Chọn model</option>${data.products.map(p=>`<option value="${p.code}" ${p.code===it.code?'selected':''}>${p.code}</option>`).join('')}</select></td><td><input value="${it.name||''}" readonly></td><td><input type="number" value="${it.qty||1}"></td><td><input class="view-cost" type="number" value="${it.cost||0}"></td><td><input value="${it.note||''}"></td><td><button class="btn danger" onclick="this.closest('tr').remove()">X</button></td>`;$('stockItems').appendChild(tr);applyPermissions()}
window.stockProductChanged=sel=>{let p=data.products.find(x=>x.code===sel.value)||{};let tr=sel.closest('tr');tr.children[1].querySelector('input').value=p.name||'';tr.children[3].querySelector('input').value=p.cost||0}
function stockItems(){return [...$('stockItems').querySelectorAll('tr')].map(tr=>({code:tr.children[0].querySelector('select').value,name:tr.children[1].querySelector('input').value,qty:+tr.children[2].querySelector('input').value||0,cost:+tr.children[3].querySelector('input').value||0,note:tr.children[4].querySelector('input').value})).filter(x=>x.code&&x.qty)}
window.saveStockVoucher=async()=>{let items=stockItems();if(!items.length)return alert('Chưa có mã hàng');let o={code:$('stockCode').value,date:$('stockDate').value,type:$('stockType').value,warehouse:$('stockWarehouse').value,note:$('stockNote').value,items,value:items.reduce((a,it)=>a+it.qty*it.cost,0),updatedAt:serverTimestamp()};if(editingStock){if(!has('editStock'))return alert('Không có quyền sửa kho');await updateDoc(doc(db,'stockVouchers',editingStock),o);await logAction('Sửa phiếu kho',o.code)}else await addDoc(col('stockVouchers'),{...o,createdAt:serverTimestamp()});await loadAll();resetStockForm()}
function renderStock(){$('stockVoucherTable').innerHTML=data.stockVouchers.sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(v=>`<tr><td>${v.code}</td><td>${v.date}</td><td>${v.type}</td><td>${(v.items||[]).length}</td><td>${money(v.value)}</td><td><button class="btn ghost" onclick="printStock('${v.id}')">In A5</button> ${has('editStock')?`<button class="btn ghost" onclick="editStock('${v.id}')">Sửa</button>`:''} ${has('deleteStock')?`<button class="btn danger" onclick="removeDoc('stockVouchers','${v.id}')">Xóa</button>`:''}</td></tr>`).join('')}
window.editStock=id=>{let v=data.stockVouchers.find(x=>x.id===id);editingStock=id;$('stockCode').value=v.code;$('stockDate').value=v.date;$('stockType').value=v.type;$('stockWarehouse').value=v.warehouse||'';$('stockNote').value=v.note||'';$('stockItems').innerHTML='';(v.items||[]).forEach(addStockItem);showPage('inventory')}
window.printStock=id=>{let v=data.stockVouchers.find(x=>x.id===id);let title=v.type==='IN'?'PHIẾU NHẬP KHO':v.type==='OUT'?'PHIẾU XUẤT KHO':'PHIẾU ĐIỀU CHỈNH KHO';let html=`<div class="print-a5"><h2 style="text-align:center">${title}</h2><p><b>Mã phiếu:</b> ${v.code} &nbsp; <b>Ngày:</b> ${v.date}<br><b>Kho:</b> ${v.warehouse||''}<br><b>Lý do:</b> ${v.note||''}</p><table><thead><tr><th>Model</th><th>Tên SP</th><th>SL</th><th>Giá vốn</th><th>Ghi chú</th></tr></thead><tbody>${(v.items||[]).map(it=>`<tr><td>${it.code}</td><td>${it.name}</td><td>${it.qty}</td><td>${money(it.cost)}</td><td>${it.note||''}</td></tr>`).join('')}</tbody></table><p style="text-align:right"><b>Giá trị:</b> ${money(v.value)}</p><div style="display:flex;justify-content:space-between;text-align:center;margin-top:35px"><div>Người lập<br><br><br></div><div>Thủ kho<br><br><br></div><div>Người nhận<br><br><br></div></div></div>`;doPrint(html)}
function renderStockBook(){$('stockBookTable').innerHTML=data.products.map(p=>{let n=0,x=0,dc=0;data.stockVouchers.forEach(v=>(v.items||[]).forEach(it=>{if(it.code===p.code){if(v.type==='IN')n+=+it.qty||0;else if(v.type==='OUT')x+=+it.qty||0;else dc+=+it.qty||0}}));let sold=data.sales.reduce((a,s)=>a+(s.items||[]).filter(it=>it.code===p.code).reduce((b,it)=>b+(+it.qty||0),0),0);x+=sold;return`<tr><td>${p.code}</td><td>${p.name}</td><td>0</td><td>${n}</td><td>${x}</td><td>${dc}</td><td><b>${n-x+dc}</b></td></tr>`}).join('')}

window.saveWarranty=async()=>{let start=$('wStart').value||today();let end=new Date(start);end.setMonth(end.getMonth()+(+$('wMonths').value||24));let o={saleId:$('wSale').value,customer:$('wCustomer').value,phone:$('wPhone').value,serial:$('wSerial').value,start,end:end.toISOString().slice(0,10),months:+$('wMonths').value||24,status:$('wStatus').value,note:$('wNote').value};if(editingWarranty)await updateDoc(doc(db,'warranties',editingWarranty),o);else await addDoc(col('warranties'),o);editingWarranty=null;['wCustomer','wPhone','wSerial','wNote'].forEach(i=>$(i).value='');await loadAll()};$('wSale').addEventListener('change',()=>{let s=data.sales.find(x=>x.id===$('wSale').value);if(s){$('wCustomer').value=s.customerName;$('wPhone').value=s.customerPhone||'';$('wSerial').value=(s.items||[]).map(i=>i.code).join(', ');$('wStart').value=s.date||today()}});
function renderWarranties(){let q=($('wSearch')?.value||'').toLowerCase();$('warrantyTable').innerHTML=data.warranties.filter(w=>(w.customer+w.phone+w.serial).toLowerCase().includes(q)).map(w=>`<tr><td>${w.customer}</td><td>${w.phone||''}</td><td>${w.serial||''}</td><td>${w.start}</td><td>${w.end}</td><td><span class="badge green">${w.status}</span></td><td><button class="btn ghost" onclick="editWarranty('${w.id}')">Sửa</button> <button class="btn danger" onclick="removeDoc('warranties','${w.id}')">Xóa</button></td></tr>`).join('')}
window.editWarranty=id=>{let w=data.warranties.find(x=>x.id===id);editingWarranty=id;$('wSale').value=w.saleId||'';$('wCustomer').value=w.customer;$('wPhone').value=w.phone||'';$('wSerial').value=w.serial||'';$('wStart').value=w.start;$('wMonths').value=w.months||24;$('wStatus').value=w.status;$('wNote').value=w.note||''}

function renderReports(){let rev=data.sales.reduce((a,s)=>a+(+s.grand||0),0),profit=data.sales.reduce((a,s)=>a+(+s.profit||0),0),debt=calcDebts().reduce((a,d)=>a+d.debt,0),stock=data.products.reduce((a,p)=>a+stockOf(p.code),0);$('reportBox').innerHTML=`<div class="report-card">Tổng doanh thu<b>${money(rev)}</b></div><div class="report-card view-cost">Tổng lợi nhuận<b>${money(profit)}</b></div><div class="report-card">Công nợ<b>${money(debt)}</b></div><div class="report-card">Tổng tồn kho<b>${stock}</b></div>`;applyPermissions()}
function renderPermissions(){let keys=Object.keys(permLabels);$('permBox').innerHTML=keys.map(k=>`<label><input type="checkbox" value="${k}"> ${permLabels[k]}</label>`).join('');$('permissionTable').innerHTML=data.users.map(u=>`<tr><td>${u.email}</td><td>${u.name||''}</td><td>${u.role}</td><td>${(u.perms||[]).map(p=>permLabels[p]||p).join(', ')}</td><td><button class="btn ghost" onclick="editPermission('${u.email}')">Sửa</button></td></tr>`).join('')}
$('uRole')?.addEventListener('change',()=>{document.querySelectorAll('#permBox input').forEach(i=>i.checked=(permissionMap[$('uRole').value]||[]).includes(i.value))});
window.saveUserPermission=async()=>{let email=$('uEmail').value.trim(),role=$('uRole').value;if(!email)return alert('Nhập email');let perms=[...document.querySelectorAll('#permBox input:checked')].map(i=>i.value);await setDoc(doc(db,'users',email),{email,name:$('uName').value,role,perms,updatedAt:serverTimestamp()});await loadAll()}
window.editPermission=email=>{let u=data.users.find(x=>x.email===email);$('uEmail').value=u.email;$('uName').value=u.name||'';$('uRole').value=u.role;document.querySelectorAll('#permBox input').forEach(i=>i.checked=(u.perms||[]).includes(i.value))}

window.removeDoc=async(name,id)=>{if(!confirm('Xóa dữ liệu này?'))return;await deleteDoc(doc(db,name,id));await logAction('Xóa '+name,id);await loadAll()}
function doPrint(html){let w=window.open('','PRINT','width=800,height=900');w.document.write(`<!doctype html><html><head><title>In phiếu</title><style>body{font-family:Arial;margin:0}.print-a5{width:148mm;min-height:210mm;padding:8mm;font-size:12px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #222;padding:5px;text-align:left}@page{size:A5;margin:0}</style></head><body>${html}<script>window.onload=()=>{window.print();setTimeout(()=>window.close(),500)}<\/script></body></html>`);w.document.close()}
window.exportCSV=(type)=>{let rows=[];if(type==='customers')rows=data.customers.map(({name,type,phone,address,discount,openingDebt})=>({name,type,phone,address,discount,openingDebt}));if(type==='products')rows=data.products.map(p=>({code:p.code,name:p.name,category:p.category,cost:p.cost,price:p.price,minStock:p.minStock,stock:stockOf(p.code)}));if(type==='prices')rows=data.prices.map(p=>({code:p.code,type:p.type,price:p.price,validFrom:p.validFrom||'',validTo:p.validTo||'',active:String(p.active)!=='false',note:p.note||''}));if(type==='sales')rows=data.sales.map(s=>({code:s.code,date:s.date,customer:s.customerName,grand:s.grand,paid:s.paid,debt:s.debt}));if(type==='stockbook')rows=data.products.map(p=>({code:p.code,name:p.name,stock:stockOf(p.code)}));let csv='\ufeff'+(rows[0]?Object.keys(rows[0]).join(',')+'\n':'')+rows.map(r=>Object.values(r).map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=type+'.csv';a.click()}
window.importCSV=async(e,type)=>{let file=e.target.files[0];if(!file)return;let txt=await file.text();let lines=txt.replace(/^\ufeff/,'').split(/\r?\n/).filter(Boolean);let heads=lines.shift().split(',').map(x=>x.replaceAll('"','').trim());for(const line of lines){let vals=line.match(/("[^"]*(""[^"]*)*"|[^,]+)/g)||[];let obj={};heads.forEach((h,i)=>obj[h]=String(vals[i]||'').replace(/^"|"$/g,'').replaceAll('""','"'));await addDoc(col(type),obj)}await loadAll();alert('Import xong')}
