import { auth, db } from './firebase-config.js';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/11.8.1/firebase-auth.js';
import { collection, doc, setDoc, addDoc, getDoc, getDocs, deleteDoc, updateDoc, serverTimestamp, query, orderBy } from 'https://www.gstatic.com/firebasejs/11.8.1/firebase-firestore.js';

const $=id=>document.getElementById(id); const money=n=>(Number(n)||0).toLocaleString('vi-VN')+'đ';
let state={user:null,profile:null,customers:[],products:[],priceLists:[],staff:[],sales:[],stockVouchers:[],receipts:[],warranties:[],expenses:[],users:[],audit:[],saleLines:[],stockLines:[],editingSale:null,editingStock:null};
const canAdmin=()=>!state.profile||state.profile.role==='Admin'||(state.profile.permissions||[]).includes('admin');
const canCost=()=>canAdmin()||['Kế toán','Quản lý'].includes(state.profile?.role);
async function loadCol(name){try{let snap=await getDocs(query(collection(db,name),orderBy('createdAt','desc')));return snap.docs.map(d=>({id:d.id,...d.data()}));}catch(e){let snap=await getDocs(collection(db,name));return snap.docs.map(d=>({id:d.id,...d.data()}));}}
async function refresh(){for(const c of ['customers','products','priceLists','staff','sales','stockVouchers','receipts','warranties','expenses','users','audit']) state[c]=await loadCol(c); renderAll();}
async function audit(action,type,data){await addDoc(collection(db,'audit'),{action,type,data,user:state.user?.email||'',createdAt:serverTimestamp(),time:new Date().toISOString()});}
async function seq(prefix,col){let n=(await loadCol(col)).length+1; return prefix+String(n).padStart(6,'0');}
function today(){return new Date().toISOString().slice(0,10)};

// In phiếu A5 ổn định trên Chrome/GitHub Pages.
// Bản trước gọi printDoc() nhưng chưa khai báo hàm nên bấm In không chạy.
function printDoc(html){
  const area = $('printArea');
  if(!area){
    alert('Không tìm thấy vùng in #printArea');
    return;
  }
  area.innerHTML = html || '';
  area.classList.add('ready-print');

  // Dùng timeout nhỏ để trình duyệt kịp render HTML/CSS trước khi gọi hộp thoại in.
  setTimeout(()=>{
    try{
      window.focus();
      window.print();
    }finally{
      // Không xoá ngay lập tức vì một số trình duyệt mở print dialog bất đồng bộ.
      setTimeout(()=>{
        area.innerHTML = '';
        area.classList.remove('ready-print');
      }, 600);
    }
  }, 150);
}
window.printDoc = printDoc;

$('loginBtn').onclick=async()=>{try{await signInWithEmailAndPassword(auth,$('email').value,$('password').value)}catch(e){alert('Đăng nhập lỗi: '+e.message)}};
$('setupAdminBtn').onclick=async()=>{try{let u=await createUserWithEmailAndPassword(auth,$('email').value,$('password').value);await setDoc(doc(db,'users',u.user.uid),{email:u.user.email,name:'Admin SIMILOCK',role:'Admin',permissions:['admin','cost','profit','sales','warehouse','accounting'],createdAt:serverTimestamp()});alert('Đã tạo Admin')}catch(e){alert(e.message)}};
$('signupStaffBtn').onclick=async()=>{try{let email=$('email').value;let allowed=state.users.find(u=>u.email===email); if(!allowed){alert('Email chưa được Admin phân quyền');return} await createUserWithEmailAndPassword(auth,email,$('password').value); alert('Đã tạo tài khoản nhân viên')}catch(e){alert(e.message)}};
$('logoutBtn').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{state.user=user;if(!user){$('loginPage').style.display='flex';$('appPage').style.display='none';return}$('loginPage').style.display='none';$('appPage').style.display='grid';let p=await getDoc(doc(db,'users',user.uid));state.profile=p.exists()?p.data():{email:user.email,role:'Admin',permissions:['admin']};$('currentUser').textContent=user.email+' • '+state.profile.role; await refresh();});

document.querySelectorAll('#menu button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
window.showPage=showPage;
function showPage(id){document.querySelectorAll('#menu button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));$('pageTitle').textContent=document.querySelector(`#menu button[data-page="${id}"]`)?.textContent.replace(/[📊🛒💵📦📘🛡️👥🔐💰👨‍💼💸📈🔑🧾☁️]/g,'').trim()||'';}

function renderAll(){renderBaseSections();renderOptions();renderDashboard();renderSales();renderReceipts();renderStock();renderStockBook();renderWarranty();renderSimpleTables();}
function renderBaseSections(){
$('customers').innerHTML=`<div class="section-head"><h2>Khách hàng</h2><div><button class="btn light" onclick="exportCSV('customers')">Export CSV</button><label class="btn light">Import CSV<input type="file" hidden onchange="importCSV(event,'customers')"></label><button class="btn primary" onclick="saveCustomer()">Lưu khách hàng</button></div></div><div class="panel"><div class="grid four"><input id="cId" type="hidden"><div><label>Tên khách</label><input id="cName"></div><div><label>Loại</label><select id="cType"><option>Khách lẻ</option><option>Khách đại lý</option><option>CTV</option></select></div><div><label>SĐT</label><input id="cPhone"></div><div><label>Địa chỉ</label><input id="cAddress"></div><div><label>Chiết khấu %</label><input id="cDiscount" type="number" value="0"></div><div><label>Công nợ đầu kỳ</label><input id="cOpeningDebt" type="number" value="0"></div></div></div><div class="panel"><table><thead><tr><th>Tên</th><th>Loại</th><th>SĐT</th><th>Địa chỉ</th><th>CK</th><th>Công nợ đầu</th><th>Hành động</th></tr></thead><tbody>${state.customers.map(c=>`<tr><td>${c.name||''}</td><td>${c.type||''}</td><td>${c.phone||''}</td><td>${c.address||''}</td><td>${c.discount||0}%</td><td>${money(c.openingDebt)}</td><td class="actions"><button class="btn light" onclick="editCustomer('${c.id}')">Sửa</button><button class="btn danger" onclick="removeDocItem('customers','${c.id}')">Xóa</button></td></tr>`).join('')}</tbody></table></div>`;
$('products').innerHTML=`<div class="section-head"><h2>Sản phẩm</h2><div><button class="btn light" onclick="exportCSV('products')">Export CSV</button><label class="btn light">Import CSV<input type="file" hidden onchange="importCSV(event,'products')"></label><button class="btn primary" onclick="saveProduct()">Lưu sản phẩm</button></div></div><div class="panel"><div class="grid four"><input id="pId" type="hidden"><div><label>Model</label><input id="pCode"></div><div><label>Tên sản phẩm</label><input id="pName"></div><div><label>Danh mục</label><input id="pCategory" value="Khóa thông minh"></div><div><label>Đơn vị</label><input id="pUnit" value="Bộ"></div><div class="costField"><label>Giá vốn</label><input id="pCost" type="number"></div><div><label>Giá bán</label><input id="pPrice" type="number"></div><div><label>Tồn tối thiểu</label><input id="pMinStock" type="number" value="2"></div><div><label>Tồn hiện tại</label><input id="pStock" type="number" value="0"></div></div></div><div class="panel"><table><thead><tr><th>Model</th><th>Tên</th><th>DM</th><th>ĐVT</th><th class="costCol">Giá vốn</th><th>Giá bán</th><th>Tồn</th><th>Hành động</th></tr></thead><tbody>${state.products.map(p=>`<tr><td><b>${p.code||''}</b></td><td>${p.name||''}</td><td>${p.category||''}</td><td>${p.unit||''}</td><td class="costCol">${money(p.cost)}</td><td>${money(p.price)}</td><td>${p.stock||0}</td><td class="actions"><button class="btn light" onclick="editProduct('${p.id}')">Sửa</button><button class="btn danger" onclick="removeDocItem('products','${p.id}')">Xóa</button></td></tr>`).join('')}</tbody></table></div>`;
$('pricelist').innerHTML=`<div class="section-head"><h2>Bảng giá</h2><button class="btn primary" onclick="savePrice()">Lưu bảng giá</button></div><div class="panel"><div class="grid four"><input id="plId" type="hidden"><div><label>Sản phẩm</label><select id="plProduct">${state.products.map(p=>`<option value="${p.id}">${p.code} - ${p.name}</option>`).join('')}</select></div><div><label>Loại khách</label><select id="plType"><option>Khách lẻ</option><option>Khách đại lý</option><option>CTV</option></select></div><div><label>Giá bán</label><input id="plPrice" type="number"></div></div></div><div class="panel"><table><thead><tr><th>Sản phẩm</th><th>Loại khách</th><th>Giá</th><th>Hành động</th></tr></thead><tbody>${(state.priceLists||[]).map(x=>`<tr><td>${x.productName}</td><td>${x.type}</td><td>${money(x.price)}</td><td></td></tr>`).join('')}</tbody></table></div>`;
$('staff').innerHTML=`<div class="section-head"><h2>Nhân viên</h2><button class="btn primary" onclick="saveStaff()">Lưu nhân viên</button></div><div class="panel"><div class="grid four"><input id="eId" type="hidden"><div><label>Họ tên</label><input id="eName"></div><div><label>Phòng ban</label><select id="eDept"><option>Sale</option><option>Kỹ thuật</option><option>Kế toán</option><option>Kho</option><option>Quản lý</option></select></div><div><label>SĐT</label><input id="ePhone"></div><div><label>% hoa hồng mặc định</label><input id="eCommission" type="number" value="0"></div></div></div><div class="panel"><table><thead><tr><th>Tên</th><th>Phòng ban</th><th>SĐT</th><th>HH%</th><th>Hành động</th></tr></thead><tbody>${state.staff.map(e=>`<tr><td>${e.name}</td><td>${e.dept}</td><td>${e.phone||''}</td><td>${e.commission||0}</td><td class="actions"><button class="btn light" onclick="editStaff('${e.id}')">Sửa</button><button class="btn danger" onclick="removeDocItem('staff','${e.id}')">Xóa</button></td></tr>`).join('')}</tbody></table></div>`;
$('expenses').innerHTML=`<div class="section-head"><h2>Chi phí</h2><button class="btn primary" onclick="saveExpense()">Lưu chi phí</button></div><div class="panel"><div class="grid four"><div><label>Khoản chi</label><input id="xName"></div><div><label>Nhóm</label><input id="xType" value="Vận hành"></div><div><label>Số tiền</label><input id="xAmount" type="number"></div><div><label>Ghi chú</label><input id="xNote"></div></div></div><div class="panel"><table><thead><tr><th>Ngày</th><th>Khoản chi</th><th>Nhóm</th><th>Số tiền</th><th>Ghi chú</th><th>Xóa</th></tr></thead><tbody>${state.expenses.map(x=>`<tr><td>${(x.time||'').slice(0,10)}</td><td>${x.name}</td><td>${x.type}</td><td>${money(x.amount)}</td><td>${x.note||''}</td><td><button class="btn danger" onclick="removeDocItem('expenses','${x.id}')">Xóa</button></td></tr>`).join('')}</tbody></table></div>`;
$('users').innerHTML=`<div class="section-head"><h2>Phân quyền</h2><button class="btn primary" onclick="saveUserRole()">Lưu phân quyền</button></div><div class="panel"><div class="grid four"><div><label>Email</label><input id="uEmail"></div><div><label>Họ tên</label><input id="uName"></div><div><label>Vai trò</label><select id="uRole"><option>Admin</option><option>Sale</option><option>Kỹ thuật</option><option>Kho</option><option>Kế toán</option><option>Quản lý</option></select></div><div><label>Quyền thêm</label><input id="uPerm" placeholder="admin,cost,profit"></div></div></div><div class="panel"><table><thead><tr><th>Email</th><th>Tên</th><th>Vai trò</th><th>Quyền</th><th>Xóa</th></tr></thead><tbody>${state.users.map(u=>`<tr><td>${u.email}</td><td>${u.name||''}</td><td>${u.role||''}</td><td>${(u.permissions||[]).join(', ')}</td><td><button class="btn danger" onclick="removeDocItem('users','${u.id}')">Xóa</button></td></tr>`).join('')}</tbody></table></div>`;
$('audit').innerHTML=`<div class="section-head"><h2>Nhật ký sửa/xóa</h2></div><div class="panel"><table><thead><tr><th>Thời gian</th><th>Người dùng</th><th>Hành động</th><th>Loại</th><th>Dữ liệu</th></tr></thead><tbody>${state.audit.map(a=>`<tr><td>${(a.time||'').replace('T',' ').slice(0,19)}</td><td>${a.user}</td><td>${a.action}</td><td>${a.type}</td><td><small>${JSON.stringify(a.data||{}).slice(0,150)}</small></td></tr>`).join('')}</tbody></table></div>`;
$('backup').innerHTML=`<div class="section-head"><h2>Backup dữ liệu</h2><button class="btn primary" onclick="backupAll()">Export toàn bộ JSON</button></div><div class="panel"><p>Bấm Export để tải toàn bộ dữ liệu hiện có. Nên lưu định kỳ mỗi tuần.</p></div>`;
$('reports').innerHTML=`<div class="section-head"><h2>Báo cáo</h2><button class="btn light" onclick="window.print()">In báo cáo</button></div><div class="kpis"><div class="kpi blue"><span>Doanh thu</span><b>${money(totalRevenue())}</b></div><div class="kpi green"><span>Lợi nhuận</span><b>${canCost()?money(totalProfit()):'Ẩn'}</b></div><div class="kpi orange"><span>Công nợ</span><b>${money(totalDebt())}</b></div><div class="kpi purple"><span>Chi phí</span><b>${money(state.expenses.reduce((s,x)=>s+Number(x.amount||0),0))}</b></div></div>`;
}
function renderOptions(){let opts=state.products.map(p=>`<option value="${p.id}">${p.code} - ${p.name}</option>`).join('');['lineProduct','stockLineProduct','wProduct'].forEach(id=>{if($(id))$(id).innerHTML=opts});let cust=state.customers.map(c=>`<option value="${c.id}">${c.name} - ${c.phone||''}</option>`).join('');['saleCustomer','wCustomer'].forEach(id=>{if($(id))$(id).innerHTML=cust});if($('customerSuggest'))$('customerSuggest').innerHTML=state.customers.map(c=>`<option value="${c.name} - ${c.phone||''}"></option>`).join('');let st=state.staff.map(e=>`<option value="${e.id}">${e.name}</option>`).join('');if($('saleStaff'))$('saleStaff').innerHTML=st;if($('receiptSale'))$('receiptSale').innerHTML=state.sales.filter(s=>Number(s.debt)>0).map(s=>`<option value="${s.id}">${s.code} - ${s.customerName} - Nợ ${money(s.debt)}</option>`).join('');}
function totalRevenue(){return state.sales.filter(s=>s.status!=='Đã hủy').reduce((a,s)=>a+Number(s.total||0),0)}function totalProfit(){let cost=0;state.sales.forEach(s=>(s.lines||[]).forEach(l=>cost+=Number(l.cost||0)*Number(l.qty||0)));return totalRevenue()-cost-state.expenses.reduce((s,x)=>s+Number(x.amount||0),0)}function totalDebt(){return state.sales.reduce((a,s)=>a+Number(s.debt||0),0)}
function topProductStats(){
  const map={};
  state.sales.forEach(s=>(s.lines||[]).forEach(l=>{
    const key=l.code||l.productId||l.name||'SP';
    if(!map[key]) map[key]={code:l.code||'',name:l.name||'',qty:0,revenue:0};
    map[key].qty+=Number(l.qty||0);
    map[key].revenue+=Number(l.total||0);
  }));
  return Object.values(map).sort((a,b)=>b.qty-a.qty).slice(0,6);
}
function renderDashboard(){
  $('kpiRevenue').textContent=money(totalRevenue());
  $('kpiProfit').textContent=canCost()?money(totalProfit()):'Ẩn';
  $('kpiDebt').textContent=money(totalDebt());
  let low=state.products.filter(p=>Number(p.stock||0)<=Number(p.minStock||2));
  $('kpiLowStock').textContent=low.length;
  if($('kpiOrderCount')) $('kpiOrderCount').textContent=state.sales.length;
  if($('kpiCustomerCount')) $('kpiCustomerCount').textContent=state.customers.length;
  if($('kpiProductCount')) $('kpiProductCount').textContent=state.products.length;
  if($('kpiStockVoucherCount')) $('kpiStockVoucherCount').textContent=state.stockVouchers.length;
  $('recentOrders').innerHTML=state.sales.slice(0,8).map(s=>`<tr><td><b>${s.code||''}</b></td><td>${s.customerName||''}</td><td>${money(s.total)}</td><td><span class="pill">${s.status||''}</span></td></tr>`).join('') || `<tr><td colspan="4" class="empty">Chưa có đơn hàng</td></tr>`;
  $('lowStockTable').innerHTML=low.slice(0,8).map(p=>`<tr><td><b>${p.code||''}</b></td><td>${p.name||''}</td><td><span class="stock-alert">${p.stock||0}</span></td></tr>`).join('') || `<tr><td colspan="3" class="empty">Kho đang ổn định</td></tr>`;
  const top=topProductStats();
  const maxQty=Math.max(...top.map(x=>x.qty),1);
  if($('topProducts')) $('topProducts').innerHTML=top.map(x=>`<tr><td><b>${x.code}</b></td><td>${x.name}</td><td>${x.qty}</td><td>${money(x.revenue)}</td></tr>`).join('') || `<tr><td colspan="4" class="empty">Chưa có dữ liệu bán hàng</td></tr>`;
  if($('topProductBars')) $('topProductBars').innerHTML=top.map((x,i)=>`<div class="bar-item"><div class="bar-head"><b>${i+1}. ${x.code} - ${x.name}</b><span>${x.qty} bộ • ${money(x.revenue)}</span></div><div class="bar-track"><i style="width:${Math.max(8,Math.round(x.qty/maxQty*100))}%"></i></div></div>`).join('') || `<div class="empty-card">Chưa có sản phẩm bán chạy. Hãy tạo đơn bán để Dashboard tự cập nhật.</div>`;
}

function calcSale(){let sub=state.saleLines.reduce((s,l)=>s+(l.qty*l.price*(1-l.discount/100)),0), rate=Number($('vatRate')?.value||0)/100, vat=0,total=sub;if($('vatMode')?.value==='add'){vat=sub*rate;total=sub+vat}else if($('vatMode')?.value==='included'){vat=sub-sub/(1+rate)}let paid=Number($('paidAmount')?.value||0);if($('subTotal')){$('subTotal').textContent=money(sub);$('vatAmount').textContent=money(vat);$('grandTotal').textContent=money(total);$('debtAmount').textContent=money(total-paid)}return{sub,vat,total,paid,debt:total-paid}}
function renderSales(){if(!$('saleDate'))return; if(!$('saleDate').value)$('saleDate').value=today(); if(!$('saleCode').value) seq('BH','sales').then(x=>$('saleCode').value=x);$('saleLines').innerHTML=state.saleLines.map((l,i)=>`<tr><td>${l.code}</td><td>${l.name}</td><td>${l.qty}</td><td>${money(l.price)}</td><td>${l.discount}</td><td>${money(l.qty*l.price*(1-l.discount/100))}</td><td><button class="btn danger" onclick="delLine(${i})">Xóa</button></td></tr>`).join('');calcSale();let q=($('saleSearch')?.value||'').toLowerCase();$('saleTable').innerHTML=state.sales.filter(s=>(s.code+s.customerName).toLowerCase().includes(q)).map(s=>`<tr><td>${s.code}</td><td>${s.date}</td><td>${s.customerName}</td><td>${money(s.total)}</td><td>${money(s.paid)}</td><td>${money(s.debt)}</td><td><span class="pill">${s.status}</span></td><td class="actions"><button class="btn light" onclick="editSale('${s.id}')">Sửa</button><button class="btn success" onclick="printSale('${s.id}')">In</button>${canAdmin()?`<button class="btn danger" onclick="deleteSale('${s.id}')">Xóa</button>`:''}</td></tr>`).join('')}
$('addLineBtn').onclick=()=>{let p=state.products.find(x=>x.id===$('lineProduct').value);if(!p)return;state.saleLines.push({productId:p.id,code:p.code,name:p.name,qty:Number($('lineQty').value||1),price:Number($('linePrice').value||p.price||0),discount:Number($('lineDiscount').value||0),cost:Number(p.cost||0)});renderSales()};
$('lineProduct').onchange=()=>{let p=state.products.find(x=>x.id===$('lineProduct').value); if(p)$('linePrice').value=p.price||0}; window.delLine=i=>{state.saleLines.splice(i,1);renderSales()};['vatMode','vatRate','paidAmount'].forEach(id=>$(id).oninput=calcSale);
$('quickCustomerBtn').onclick=async()=>{let name=prompt('Tên khách hàng mới'); if(!name)return;let phone=prompt('Số điện thoại')||'';let ref=await addDoc(collection(db,'customers'),{name,phone,type:'Khách lẻ',discount:0,createdAt:serverTimestamp()});await audit('create','customers',{name,phone});await refresh();$('saleCustomer').value=ref.id};
$('saveSaleBtn').onclick=async()=>{if(!state.saleLines.length){alert('Chưa có hàng hóa');return}let c=state.customers.find(x=>x.id===$('saleCustomer').value)||{};let st=state.staff.find(x=>x.id===$('saleStaff').value)||{};let totals=calcSale();let data={code:$('saleCode').value,date:$('saleDate').value,status:$('saleStatus').value,customerId:c.id||'',customerName:c.name||'',customerPhone:c.phone||'',staffId:st.id||'',staffName:st.name||'',vatMode:$('vatMode').value,vatRate:Number($('vatRate').value||0),note:$('saleNote').value,lines:state.saleLines,subtotal:totals.sub,vat:totals.vat,total:totals.total,paid:totals.paid,debt:totals.debt,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};if(state.editingSale){await updateDoc(doc(db,'sales',state.editingSale),data);await audit('update','sales',data)}else{await addDoc(collection(db,'sales'),data);await audit('create','sales',data);for(const l of state.saleLines){let p=state.products.find(x=>x.id===l.productId); if(p) await updateDoc(doc(db,'products',p.id),{stock:Number(p.stock||0)-Number(l.qty||0)})}}newSale();await refresh()};
function newSale(){state.editingSale=null;state.saleLines=[];['saleNote'].forEach(id=>$(id).value='');$('paidAmount').value=0;$('saleCode').value='';seq('BH','sales').then(x=>$('saleCode').value=x);renderSales()}$('newSaleBtn').onclick=newSale;
window.editSale=id=>{if(!canAdmin()){alert('Chỉ Admin được sửa đơn');return}let s=state.sales.find(x=>x.id===id);state.editingSale=id;state.saleLines=[...(s.lines||[])];$('saleCode').value=s.code;$('saleDate').value=s.date;$('saleStatus').value=s.status;$('saleCustomer').value=s.customerId;$('saleStaff').value=s.staffId;$('vatMode').value=s.vatMode;$('vatRate').value=s.vatRate;$('paidAmount').value=s.paid;$('saleNote').value=s.note||'';renderSales();window.scrollTo(0,0)};
window.deleteSale=async id=>{if(!canAdmin())return;if(confirm('Xóa phiếu bán?')){let s=state.sales.find(x=>x.id===id);await deleteDoc(doc(db,'sales',id));await audit('delete','sales',s);await refresh()}};
function salePrintHtml(s){return `<div class="print-doc"><h2>PHIẾU BÁN HÀNG</h2><div class="print-meta"><div>Mã: <b>${s.code}</b></div><div>Ngày: ${s.date}</div><div>Khách: ${s.customerName}</div><div>SĐT: ${s.customerPhone||''}</div><div>NV: ${s.staffName||''}</div><div>Trạng thái: ${s.status}</div></div><table><thead><tr><th>Model</th><th>Tên hàng</th><th>SL</th><th>Đơn giá</th><th>CK</th><th>Thành tiền</th></tr></thead><tbody>${(s.lines||[]).map(l=>`<tr><td>${l.code}</td><td>${l.name}</td><td>${l.qty}</td><td>${money(l.price)}</td><td>${l.discount}%</td><td>${money(l.qty*l.price*(1-l.discount/100))}</td></tr>`).join('')}</tbody></table><h3 style="text-align:right">Tổng thanh toán: ${money(s.total)}</h3><p style="text-align:right">Đã thu: ${money(s.paid)} | Còn nợ: ${money(s.debt)}</p><div class="print-sign"><div>Khách hàng<br><br><br>................</div><div>Người lập phiếu<br><br><br>................</div></div></div>`}
window.printSale=id=>{let s=state.sales.find(x=>x.id===id);printDoc(salePrintHtml(s))};$('printSaleBtn').onclick=()=>{let data={code:$('saleCode').value,date:$('saleDate').value,status:$('saleStatus').value,customerName:state.customers.find(x=>x.id===$('saleCustomer').value)?.name||'',customerPhone:state.customers.find(x=>x.id===$('saleCustomer').value)?.phone||'',staffName:state.staff.find(x=>x.id===$('saleStaff').value)?.name||'',lines:state.saleLines,...calcSale()};data.total=data.total;data.paid=data.paid;data.debt=data.debt;printDoc(salePrintHtml(data))};$('saleSearch').oninput=renderSales;

function renderReceipts(){if(!$('receiptDate'))return;if(!$('receiptDate').value)$('receiptDate').value=today();if(!$('receiptCode').value)seq('PT','receipts').then(x=>$('receiptCode').value=x);$('debtTable').innerHTML=state.customers.map(c=>{let ss=state.sales.filter(s=>s.customerId===c.id);let buy=ss.reduce((a,s)=>a+Number(s.total||0),0)+Number(c.openingDebt||0), paid=ss.reduce((a,s)=>a+Number(s.paid||0),0);return `<tr><td>${c.name}</td><td>${money(buy)}</td><td>${money(paid)}</td><td><b>${money(buy-paid)}</b></td></tr>`}).join('');$('receiptTable').innerHTML=state.receipts.map(r=>`<tr><td>${r.code}</td><td>${r.date}</td><td>${r.saleCode}</td><td>${money(r.amount)}</td><td>${r.note||''}</td></tr>`).join('')}
$('saveReceiptBtn').onclick=async()=>{let s=state.sales.find(x=>x.id===$('receiptSale').value);if(!s)return;let amt=Number($('receiptAmount').value||0);await addDoc(collection(db,'receipts'),{code:$('receiptCode').value,date:$('receiptDate').value,saleId:s.id,saleCode:s.code,amount:amt,note:$('receiptNote').value,createdAt:serverTimestamp()});await updateDoc(doc(db,'sales',s.id),{paid:Number(s.paid||0)+amt,debt:Number(s.debt||0)-amt,status:(Number(s.debt||0)-amt)<=0?'Đã thu tiền':s.status});await audit('create','receipts',{sale:s.code,amount:amt});$('receiptCode').value='';$('receiptAmount').value='';$('receiptNote').value='';await refresh()};

function renderStock(){if(!$('stockDate'))return;if(!$('stockDate').value)$('stockDate').value=today();if(!$('stockCode').value)seq('NK','stockVouchers').then(x=>$('stockCode').value=x);$('stockLines').innerHTML=state.stockLines.map((l,i)=>`<tr><td>${l.code}</td><td>${l.name}</td><td>${l.qty}</td><td>${l.note||''}</td><td><button class="btn danger" onclick="delStockLine(${i})">Xóa</button></td></tr>`).join('');$('stockVoucherTable').innerHTML=state.stockVouchers.map(v=>`<tr><td>${v.code}</td><td>${v.date}</td><td>${v.type}</td><td>${(v.lines||[]).length}</td><td>${v.reason||''}</td><td class="actions"><button class="btn light" onclick="editStock('${v.id}')">Sửa</button><button class="btn success" onclick="printStock('${v.id}')">In</button>${canAdmin()?`<button class="btn danger" onclick="deleteStock('${v.id}')">Xóa</button>`:''}</td></tr>`).join('')}
$('stockType').onchange=()=>{let pre=$('stockType').value.includes('Nhập')?'NK':$('stockType').value.includes('Xuất')?'XK':'DC';seq(pre,'stockVouchers').then(x=>$('stockCode').value=x)};
$('addStockLineBtn').onclick=()=>{let p=state.products.find(x=>x.id===$('stockLineProduct').value);if(!p)return;state.stockLines.push({productId:p.id,code:p.code,name:p.name,qty:Number($('stockLineQty').value||1),note:$('stockLineNote').value});renderStock()}; window.delStockLine=i=>{state.stockLines.splice(i,1);renderStock()};
$('saveStockBtn').onclick=async()=>{if(!state.stockLines.length){alert('Chưa có hàng hóa');return}let data={code:$('stockCode').value,date:$('stockDate').value,type:$('stockType').value,reason:$('stockReason').value,lines:state.stockLines,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};if(state.editingStock){await updateDoc(doc(db,'stockVouchers',state.editingStock),data);await audit('update','stockVouchers',data)}else{await addDoc(collection(db,'stockVouchers'),data);await applyStock(data);await audit('create','stockVouchers',data)}newStock();await refresh()};
async function applyStock(v){let sign=(v.type==='Nhập kho'||v.type==='Điều chỉnh tăng')?1:-1;for(const l of v.lines){let p=state.products.find(x=>x.id===l.productId);if(p)await updateDoc(doc(db,'products',p.id),{stock:Number(p.stock||0)+sign*Number(l.qty||0)})}}
function newStock(){state.editingStock=null;state.stockLines=[];$('stockReason').value='';$('stockCode').value='';renderStock()}$('newStockBtn').onclick=newStock;
window.editStock=id=>{if(!canAdmin()){alert('Chỉ Admin được sửa phiếu kho');return}let v=state.stockVouchers.find(x=>x.id===id);state.editingStock=id;state.stockLines=[...(v.lines||[])];$('stockCode').value=v.code;$('stockDate').value=v.date;$('stockType').value=v.type;$('stockReason').value=v.reason||'';renderStock();window.scrollTo(0,0)};
window.deleteStock=async id=>{if(confirm('Xóa phiếu kho? Lưu ý tồn kho không tự hoàn nguyên trong bản web tĩnh này.')){let v=state.stockVouchers.find(x=>x.id===id);await deleteDoc(doc(db,'stockVouchers',id));await audit('delete','stockVouchers',v);await refresh()}};
function stockPrintHtml(v){return `<div class="print-doc"><h2>PHIẾU ${v.type.toUpperCase()}</h2><div class="print-meta"><div>Mã: <b>${v.code}</b></div><div>Ngày: ${v.date}</div><div>Loại: ${v.type}</div><div>Lý do: ${v.reason||''}</div></div><table><thead><tr><th>Model</th><th>Tên hàng</th><th>SL</th><th>Ghi chú</th></tr></thead><tbody>${(v.lines||[]).map(l=>`<tr><td>${l.code}</td><td>${l.name}</td><td>${l.qty}</td><td>${l.note||''}</td></tr>`).join('')}</tbody></table><div class="print-sign"><div>Thủ kho<br><br><br>................</div><div>Người lập phiếu<br><br><br>................</div></div></div>`}
window.printStock=id=>{printDoc(stockPrintHtml(state.stockVouchers.find(x=>x.id===id)))};$('printStockBtn').onclick=()=>{printDoc(stockPrintHtml({code:$('stockCode').value,date:$('stockDate').value,type:$('stockType').value,reason:$('stockReason').value,lines:state.stockLines}))};
function renderStockBook(){if(!$('stockBookTable'))return;$('stockBookTable').innerHTML=state.products.map(p=>{let inq=0,out=0,adj=0;state.stockVouchers.forEach(v=>(v.lines||[]).filter(l=>l.productId===p.id).forEach(l=>{if(v.type==='Nhập kho')inq+=l.qty;else if(v.type==='Xuất kho')out+=l.qty;else adj+=v.type.includes('tăng')?l.qty:-l.qty}));return `<tr><td>${p.code}</td><td>${p.name}</td><td><b>${p.stock||0}</b></td><td>${inq}</td><td>${out}</td><td>${adj}</td></tr>`}).join('')}
$('exportStockBookBtn').onclick=()=>exportRows('stockbook',state.products.map(p=>({code:p.code,name:p.name,stock:p.stock||0})));

function renderWarranty(){if(!$('wInstallDate'))return;if(!$('wInstallDate').value)$('wInstallDate').value=today();let q=($('wSearch')?.value||'').toLowerCase();$('warrantyTable').innerHTML=state.warranties.filter(w=>(w.customerName+w.phone+w.serial).toLowerCase().includes(q)).map(w=>`<tr><td>${w.customerName}</td><td>${w.phone}</td><td>${w.productCode}</td><td>${w.serial}</td><td>${w.installDate}</td><td>${w.endDate}</td><td><span class="pill">${w.status}</span></td><td><button class="btn danger" onclick="removeDocItem('warranties','${w.id}')">Xóa</button></td></tr>`).join('')}
$('saveWarrantyBtn').onclick=async()=>{let c=state.customers.find(x=>x.id===$('wCustomer').value)||{},p=state.products.find(x=>x.id===$('wProduct').value)||{};let d=new Date($('wInstallDate').value);d.setMonth(d.getMonth()+Number($('wMonths').value||24));await addDoc(collection(db,'warranties'),{customerId:c.id,customerName:c.name,phone:c.phone||'',productId:p.id,productCode:p.code,productName:p.name,serial:$('wSerial').value,installDate:$('wInstallDate').value,months:Number($('wMonths').value||24),endDate:d.toISOString().slice(0,10),status:$('wStatus').value,note:$('wNote').value,createdAt:serverTimestamp()});await audit('create','warranties',{customer:c.name,serial:$('wSerial').value});await refresh()};$('wSearch').oninput=renderWarranty;

function renderSimpleTables(){document.querySelectorAll('.costCol,.costField').forEach(e=>e.style.display=canCost()?'':'none')}
window.saveCustomer=async()=>{let data={name:$('cName').value,type:$('cType').value,phone:$('cPhone').value,address:$('cAddress').value,discount:Number($('cDiscount').value||0),openingDebt:Number($('cOpeningDebt').value||0),createdAt:serverTimestamp()};let id=$('cId').value;if(id){await updateDoc(doc(db,'customers',id),data);await audit('update','customers',data)}else{await addDoc(collection(db,'customers'),data);await audit('create','customers',data)}await refresh()};
window.editCustomer=id=>{let c=state.customers.find(x=>x.id===id);['Id','Name','Type','Phone','Address','Discount','OpeningDebt'].forEach(k=>{let el=$('c'+k);if(el)el.value=c[k.charAt(0).toLowerCase()+k.slice(1)]||''})};
window.saveProduct=async()=>{let data={code:$('pCode').value,name:$('pName').value,category:$('pCategory').value,unit:$('pUnit').value,cost:Number($('pCost').value||0),price:Number($('pPrice').value||0),minStock:Number($('pMinStock').value||2),stock:Number($('pStock').value||0),createdAt:serverTimestamp()};let id=$('pId').value;if(id){await updateDoc(doc(db,'products',id),data);await audit('update','products',data)}else{await addDoc(collection(db,'products'),data);await audit('create','products',data)}await refresh()};
window.editProduct=id=>{let p=state.products.find(x=>x.id===id);$('pId').value=p.id;$('pCode').value=p.code;$('pName').value=p.name;$('pCategory').value=p.category;$('pUnit').value=p.unit;$('pCost').value=p.cost;$('pPrice').value=p.price;$('pMinStock').value=p.minStock;$('pStock').value=p.stock};
window.savePrice=async()=>{let p=state.products.find(x=>x.id===$('plProduct').value)||{};let data={productId:p.id,productName:(p.code||'')+' - '+(p.name||''),type:$('plType').value,price:Number($('plPrice').value||0),createdAt:serverTimestamp()};let id=$('plId').value;if(id)await updateDoc(doc(db,'priceLists',id),data);else await addDoc(collection(db,'priceLists'),data);await audit(id?'update':'create','priceLists',data);await refresh()};
window.saveStaff=async()=>{let data={name:$('eName').value,dept:$('eDept').value,phone:$('ePhone').value,commission:Number($('eCommission').value||0),createdAt:serverTimestamp()};let id=$('eId').value;if(id)await updateDoc(doc(db,'staff',id),data);else await addDoc(collection(db,'staff'),data);await audit(id?'update':'create','staff',data);await refresh()};window.editStaff=id=>{let e=state.staff.find(x=>x.id===id);$('eId').value=e.id;$('eName').value=e.name;$('eDept').value=e.dept;$('ePhone').value=e.phone;$('eCommission').value=e.commission||0};
window.saveExpense=async()=>{let data={name:$('xName').value,type:$('xType').value,amount:Number($('xAmount').value||0),note:$('xNote').value,time:new Date().toISOString(),createdAt:serverTimestamp()};await addDoc(collection(db,'expenses'),data);await audit('create','expenses',data);await refresh()};
window.saveUserRole=async()=>{let data={email:$('uEmail').value,name:$('uName').value,role:$('uRole').value,permissions:$('uPerm').value.split(',').map(x=>x.trim()).filter(Boolean),createdAt:serverTimestamp()};await addDoc(collection(db,'users'),data);await audit('create','users',data);await refresh()};
window.removeDocItem=async(col,id)=>{if(!canAdmin()&&!['customers','products'].includes(col)){alert('Không đủ quyền');return}if(confirm('Xóa dữ liệu này?')){let old=state[col]?.find(x=>x.id===id);await deleteDoc(doc(db,col,id));await audit('delete',col,old);await refresh()}};
window.exportCSV=col=>exportRows(col,state[col]||[]);function exportRows(name,rows){let csv='';if(rows.length){let keys=Object.keys(rows[0]).filter(k=>typeof rows[0][k]!=='object');csv=keys.join(',')+'\n'+rows.map(r=>keys.map(k=>'"'+String(r[k]??'').replaceAll('"','""')+'"').join(',')).join('\n')}let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=name+'.csv';a.click()}
window.importCSV=(ev,col)=>{let f=ev.target.files[0];if(!f)return;let r=new FileReader();r.onload=async()=>{let lines=r.result.split(/\r?\n/).filter(Boolean),keys=lines.shift().split(',').map(x=>x.replaceAll('"',''));for(const line of lines){let vals=line.match(/("[^"]*(""[^"]*)*"|[^,]+)/g)||[];let obj={};keys.forEach((k,i)=>obj[k]=String(vals[i]||'').replace(/^"|"$/g,'').replaceAll('""','"'));obj.createdAt=serverTimestamp();await addDoc(collection(db,col),obj)}await audit('import',col,{count:lines.length});await refresh()};r.readAsText(f)};
window.backupAll=()=>{let data={customers:state.customers,products:state.products,staff:state.staff,sales:state.sales,stockVouchers:state.stockVouchers,receipts:state.receipts,warranties:state.warranties,expenses:state.expenses,users:state.users};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='similock-backup-'+today()+'.json';a.click()};
