const DEFAULT_RECEIPT_PAYMENT_METHOD='Chuyển khoản';
function financeDocDate(o){return String(o.date||'').slice(0,10)}
function isUnknownPaymentMethod(v){return !String(v||'').trim() || ['Chưa chọn','Chưa xác định','Chưa khai báo','undefined','null'].includes(String(v||'').trim())}
function normalizePaymentMethod(v){const m=String(v??'').trim(); return isUnknownPaymentMethod(m)?'':m}
function receiptEffectivePaymentMethod(r={}){return normalizePaymentMethod(r.paymentMethod||r.payMethod||r.method)||DEFAULT_RECEIPT_PAYMENT_METHOD}
function receiptDedupKey(r={}){const saleKey=String(r.saleId||r.debtKey||r.saleCode||r.customerCode||r.customerPhone||r.customerId||'');const date=String(financeDocDate(r)||r.date||'');const amount=String(Math.round((+r.amount||0)*100)/100);const method=String(normalizePaymentMethod(r.paymentMethod||r.payMethod||r.method)||'');return saleKey?['receipt',saleKey,date,amount,method].join('|'):['receipt-id',r.id||r.code||'',date,amount,method].join('|')}
function uniqueReceiptsForFinance(rows=[]){const seen=new Set(), out=[]; rows.forEach(r=>{const k=receiptDedupKey(r); if(!seen.has(k)){seen.add(k); out.push(r)}}); return out}
function cashbookRows(data,from,to){const rows=[];const seen=new Set();const pushRow=r=>{if(!r.date||r.date<from||r.date>to)return;const key=[r.source,r.id||'',r.code||'',r.type,r.date,r.income||0,r.expense||0].join('|');if(seen.has(key))return;seen.add(key);rows.push(r)};uniqueReceiptsForFinance(data.receipts.filter(r=>!r.canceled)).forEach(r=>{const amount=+r.amount||0;if(amount<=0)return;const date=financeDocDate(r);if(!date)return;pushRow({id:r.id,date,code:r.code,type:'Thu',content:'Phiếu thu',paymentMethod:receiptEffectivePaymentMethod(r),income:amount,expense:0,source:'receipt'})});data.expenses.filter(e=>e.category!=='Lương').forEach(e=>{const amount=+e.amount||0;if(amount<=0)return;const date=financeDocDate(e);if(!date)return;pushRow({id:e.id,date,code:e.code,type:'Chi',content:'Phiếu chi',paymentMethod:normalizePaymentMethod(e.paymentMethod)||'Tiền mặt',income:0,expense:amount,source:'expense'})});data.salaries.forEach(e=>{const amount=+(e.total||e.amount)||0;if(amount<=0)return;const date=financeDocDate(e);if(!date)return;pushRow({id:e.id,date,code:e.code,type:'Chi',content:'Chi lương',paymentMethod:normalizePaymentMethod(e.paymentMethod)||'Tiền mặt',income:0,expense:amount,source:'salary'})});return rows.sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
function dashboardCollected(data,from,to){return uniqueReceiptsForFinance(data.receipts.filter(r=>!r.canceled)).filter(r=>{const d=financeDocDate(r);return d&&d>=from&&d<=to}).reduce((a,r)=>a+(+r.amount||0),0)}
function assertEq(name,got,want){if(got!==want){throw new Error(`${name}: got ${got}, want ${want}`)}console.log('OK',name,got)}
const data={sales:[{id:'s1',code:'BH1',date:'2026-06-01',grand:10000000,paid:10000000,paymentMethod:'Tiền mặt'}],receipts:[{id:'r1',code:'PT1',saleId:'s1',date:'2026-06-01',amount:10000000,paymentMethod:''},{id:'r1dup',code:'PT1-copy',saleId:'s1',date:'2026-06-01',amount:10000000,paymentMethod:''},{id:'r2',code:'PT2',saleId:'s0',date:'2026-06-02',amount:5000000,paymentMethod:'Tiền mặt'}],expenses:[{id:'e1',code:'PC1',date:'2026-06-02',amount:1000000,paymentMethod:'Tiền mặt'}],salaries:[{id:'l1',code:'L1',date:'2026-06-03',total:2000000,paymentMethod:'Chuyển khoản'}]};
const rows=cashbookRows(data,'2026-06-01','2026-06-30');
assertEq('không cộng paid trực tiếp trên phiếu bán', rows.filter(r=>r.source==='sale_direct_legacy').length, 0);
assertEq('tổng thu sổ quỹ chỉ bằng phiếu thu đã chống trùng', rows.reduce((a,r)=>a+r.income,0), 15000000);
assertEq('thực thu dashboard khớp tổng phiếu thu', dashboardCollected(data,'2026-06-01','2026-06-30'), 15000000);
assertEq('tổng chi sổ quỹ', rows.reduce((a,r)=>a+r.expense,0), 3000000);
assertEq('phiếu thu thiếu phương thức mặc định chuyển khoản', rows.find(r=>r.code==='PT1').paymentMethod, 'Chuyển khoản');
